import { GalleryData } from '@/types/gallery';

export const defaultGalleryData: GalleryData = {
  stats: {
    totalMilestones: '120+',
    activeCampusLabs: '50+',
    studentsReached: '10,000+',
    competitionsWon: '48+',
  },

  albums: [
    {
      id: 'album-dps-varanasi',
      slug: 'dps-varanasi-robotics-ai-ecosystem',
      schoolName: 'Delhi Public School, Varanasi',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      implementationDate: 'July 2026',
      headline: 'DPS Varanasi × Shorai: Flagship Robotics & AI Hub Launch',
      subtitle: 'Complete 30-day turnkey transformation of a 750 sq. ft. campus space into an advanced robotics, drone telemetry, and computer vision lab.',
      storyNarrative: 'In partnership with Shorai and SEG Academy (15+ years educational excellence), Delhi Public School Varanasi inaugurated its state-of-the-art STEM & AI Innovation Lab. Over 1,200 students from Grades 3 to 12 now engage in hands-on robotics engineering, micro-controller circuit building, and autonomous flight testing during weekly curriculum periods.',
      technologiesCovered: [
        'Robotics & Automation Bays',
        'Artificial Intelligence & Edge ML',
        'Autonomous Drone Aerodynamics',
        'IoT Microcontroller Stations',
        '3D Printing & Rapid Prototyping',
        'NEP 2020 Grade-Wise Progressive Pedagogy',
      ],
      heroImage: '/images/shorai-images/shorai-smart-class-coding-lecture.jpg',
      galleryItemIds: ['gal-1', 'gal-2', 'gal-3', 'gal-4', 'gal-5'],
      outcomes: [
        '100% student enrollment across Middle and High School in weekly lab sessions',
        'Full-time on-campus certified Master Trainer deployed and managed by Shorai',
        'School team qualified for Regional World Robot Olympiad (WRO) 2026',
        'Aligned with Viksit Bharat @2047 national innovation roadmap',
      ],
      principalQuote: {
        quote: 'Shorai brought not just hardware kits, but a complete 360° turnkey transformation. The dedicated on-ground mentor, AI-powered LMS tracking, and structured NEP 2020 curriculum have created visible excitement among our students and parents.',
        author: 'Dr. S. K. Mukherjee',
        designation: 'Principal, DPS Varanasi',
      },
    },
    {
      id: 'album-kolkata-stem',
      slug: 'kolkata-stem-innovation-center',
      schoolName: 'Shorai STEM Innovation Campus (SEG Academy)',
      city: 'Kolkata',
      state: 'West Bengal',
      implementationDate: 'May 2026',
      headline: 'Kolkata Regional Research Hub: Autonomous Drone & AI Aviation',
      subtitle: 'Eastern India central hub for master faculty training, advanced robotics research, and inter-school hackathons.',
      storyNarrative: 'The Shorai Kolkata Research Campus (119/114 Ramkrishna Road, Khardaha) serves as the master pedagogical and testing center for school faculty across Eastern India. Here, teachers undergo 40 hours of rigorous hands-on enablement in AI tools, cyber security, and robotics before classroom deployment.',
      technologiesCovered: [
        'Drone Flight Simulators & ESC Tuning',
        '3D Additive Design & Slicing Workstations',
        'Python Embedded Logic Sandboxes',
        'Cyber Security & Safe Digital Citizenship',
      ],
      heroImage: '/images/shorai-images/shorai-robotics-summer-camp-workshop.jpg',
      galleryItemIds: ['gal-6', 'gal-7', 'gal-8', 'gal-9'],
      outcomes: [
        'Over 150 school educators certified in NEP 2020 STEM pedagogy',
        'Central flight testing cage for autonomous UAV obstacle navigation',
        'Incubated 12 student prototypes into regional science exhibitions',
      ],
    },
    {
      id: 'album-lucknow-public',
      slug: 'lucknow-public-school-ai-coding',
      schoolName: 'Lucknow Public Collegiate',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      implementationDate: 'August 2026',
      headline: 'Empowering 800+ Young Coders in Lucknow',
      subtitle: 'Transitioning from screen-only coding to tactile robotics, sensor integration, and real-world problem solving.',
      storyNarrative: 'Lucknow Public Collegiate partnered with Shorai to implement the 5-Stage Progressive Learning Journey. Students start with visual block logic in Primary and advance to Python, IoT sensors, and machine learning models in Senior Secondary.',
      technologiesCovered: [
        'Visual Block Programming (Scratch & Blockly)',
        'Arduino Embedded C++ Systems',
        'Line Following & Obstacle Avoidance Rovers',
        'IoT Weather Stations & Sensor Logging',
      ],
      heroImage: '/images/shorai-images/shorai-students-robotics-kit-lab.jpg',
      galleryItemIds: ['gal-10', 'gal-11', 'gal-12'],
      outcomes: [
        '24 student-built smart automation projects showcased at the Annual Science Fair',
        '100% curriculum compliance with CBSE Coding Skill Subject guidelines',
        '92% parent satisfaction reported during Termly Innovation Open Days',
      ],
    },
  ],

  transformations: [
    {
      id: 'trans-1',
      school: 'DPS Varanasi Campus',
      city: 'Varanasi, Uttar Pradesh',
      beforeDescription: 'Standard computer room with theoretical textbook lectures and zero hands-on electronics hardware.',
      beforeImage: '/images/shorai-images/shorai-matrix-school-robot-team.jpg',
      transformationDetails: 'Installed 8 modular hexagonal workbenches, dedicated flight testing cage, complete sensor inventory, safety gear, and deployed a full-time Master Trainer in 21 days.',
      afterDescription: 'Fully active Innovation Lab where students build autonomous rovers, test drone ESC circuits, and write machine learning classifiers weekly.',
      afterImage: '/images/shorai-images/shorai-smart-class-coding-lecture.jpg',
      impactMetrics: {
        studentsTrained: '1,200+',
        projectsBuilt: '45+',
        competitionsWon: '4 Regional Medals',
      },
    },
    {
      id: 'trans-2',
      school: 'Heritage Global School',
      city: 'Kolkata, West Bengal',
      beforeDescription: 'Disused science storage room with outdated display equipment.',
      beforeImage: '/images/shorai-images/shorai-students-tuning-rover.jpg',
      transformationDetails: 'Renovated into an advanced AI & IoT Tinkering Bay with 3D printers, laser calibration, and smart micro-controllers under the Shorai 360° model.',
      afterDescription: 'Inter-school competition incubation zone with active student robotics teams winning Atal Tinkering Marathon awards.',
      afterImage: '/images/shorai-images/shorai-robotics-summer-camp-workshop.jpg',
      impactMetrics: {
        studentsTrained: '650+',
        projectsBuilt: '32+',
        competitionsWon: '1st Prize State Innovation',
      },
    },
  ],

  items: [
    {
      id: 'gal-1',
      title: 'Autonomous Obstacle Rover Calibration',
      caption: 'Grade 8 students configuring ultrasonic sensors and motor drivers on their autonomous obstacle rovers in the robotics lab.',
      school: 'Daffodils Public School',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'August 2026',
      category: 'robotics_ai',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-images/shorai-students-robotics-kit-lab.jpg',
      videoUrl: '/images/shorai-images/shorai-robotics-lab-demo-1.mp4',
      tags: ['Robotics', 'Ultrasonic Sensors', 'Arduino', 'Middle School'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-2',
      title: 'Humanoid Robot Telemetry & Logic Presentation',
      caption: 'Student engineering team demonstrating a custom mobile humanoid robot with integrated block code telemetry controls.',
      school: 'Daffodils Public School',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'robotics_ai',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-humanoid-robot-presentation.jpg',
      tags: ['Humanoid Robot', 'Telemetry', 'Block Coding', 'Innovation'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-3',
      title: 'Tactile Breadboard Circuit Experimentation',
      caption: 'Student assembling jumper wires, LED matrix arrays, and micro-controller circuits on a breadboard during lab session.',
      school: 'Daffodils Public School',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'coding_stem',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-student-breadboard-wiring.jpg',
      tags: ['Circuits', 'Breadboard', 'STEM', 'Electronics'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-4',
      title: 'Hands-On Robotics Lab Collaborative Sprint',
      caption: 'Students collaborating across workstations assembling motors, chassis kits, and robotic rovers during curriculum hours.',
      school: 'Daffodils Public School',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'inaugurations_atl',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-images/shorai-students-collaboration-lab.jpg',
      videoUrl: '/images/shorai-images/shorai-robotics-lab-demo-2.mp4',
      tags: ['Innovation Lab', 'Collaboration', 'Turnkey Setup', 'Classroom'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-5',
      title: 'Robotics Summer Camp Team Showcase',
      caption: 'Young innovators showcasing their completed rover models and embedded circuits at the Alpha Edubots Summer Camp.',
      school: 'Alpha Edubots Campus',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'August 2026',
      category: 'competitions_wro',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-girls-robotics-summer-camp.jpg',
      tags: ['Summer Camp', 'Rovers', 'Young Innovators', 'Competition'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-6',
      title: 'Smart Class Interactive Coding & Pedagogy',
      caption: 'Certified Shorai Master Trainer guiding students through interactive visual block programming and logical sequencing on smart screen.',
      school: 'Shorai STEM Center (SEG Academy)',
      schoolSlug: 'kolkata-stem-innovation-center',
      city: 'Kolkata',
      state: 'West Bengal',
      date: 'June 2026',
      category: 'workshops_training',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-images/shorai-smart-class-coding-lecture.jpg',
      tags: ['Smart Class', 'Teacher Enablement', 'Block Coding', 'Pedagogy'],
      albumId: 'album-kolkata-stem',
    },
    {
      id: 'gal-7',
      title: 'Modular Hardware Assembly & Sensor Calibration',
      caption: 'Students assembling Quarky robotics kits with modular sensors, learning tactile motor calibration and logic gates.',
      school: 'Shorai STEM Center (SEG Academy)',
      schoolSlug: 'kolkata-stem-innovation-center',
      city: 'Kolkata',
      state: 'West Bengal',
      date: 'May 2026',
      category: 'robotics_ai',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-images/shorai-students-quarky-robot-assembly.jpg',
      tags: ['Modular Robotics', 'Quarky Kit', 'Sensors', 'Hardware'],
      albumId: 'album-kolkata-stem',
    },
    {
      id: 'gal-8',
      title: 'Interactive AI Computer Vision Model Deployment',
      caption: 'Student presenting real-time PictoBlox AI computer vision and image recognition model running on interactive smart display.',
      school: 'Matrix High School',
      city: 'Kolkata',
      state: 'West Bengal',
      date: 'May 2026',
      category: 'robotics_ai',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-smartboard-ai-vision-coding.jpg',
      tags: ['Computer Vision', 'PictoBlox', 'AI Vision', 'Smart Board'],
    },
    {
      id: 'gal-9',
      title: 'Visual Block to Python Progression Bootcamp',
      caption: 'Students programming autonomous line-following algorithms on laptop connected to modular robotic rovers at camp workshop.',
      school: 'Lucknow Public Collegiate',
      schoolSlug: 'lucknow-public-school-ai-coding',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      date: 'August 2026',
      category: 'coding_stem',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-images/shorai-robotics-summer-camp-workshop.jpg',
      tags: ['Bootcamp', 'Block Coding', 'Laptop Coding', 'Robotics Camp'],
      albumId: 'album-lucknow-public',
    },
    {
      id: 'gal-10',
      title: 'Autonomous Rover Hardware Tuning',
      caption: 'Middle school students assembling servo motors, structural brackets, and motor driver boards for competition rovers.',
      school: 'Matrix High School',
      schoolSlug: 'lucknow-public-school-ai-coding',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      date: 'August 2026',
      category: 'coding_stem',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-students-teamwork-rover.jpg',
      tags: ['Hardware Tuning', 'Servo Motors', 'Teamwork', 'STEM'],
      albumId: 'album-lucknow-public',
    },
    {
      id: 'gal-11',
      title: 'Line Following Rover Speed Challenge',
      caption: 'Student engineering squad configuring chassis balance and infrared sensor alignment for high-speed track navigation.',
      school: 'Matrix High School',
      schoolSlug: 'lucknow-public-school-ai-coding',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'robotics_ai',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-matrix-school-robot-team.jpg',
      tags: ['PID Tuning', 'Line Follower', 'Matrix School', 'Engineering'],
      albumId: 'album-lucknow-public',
    },
    {
      id: 'gal-12',
      title: 'Robotics Innovation Showcase & Project Review',
      caption: 'Student innovators presenting multi-terrain exploration rover and obstacle avoidance prototypes at summer camp showcase.',
      school: 'Alpha Edubots Campus',
      city: 'Kolkata',
      state: 'West Bengal',
      date: 'June 2026',
      category: 'competitions_wro',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-robotics-champions-camp.jpg',
      tags: ['Showcase', 'Rover Prototype', 'Innovation', 'State Award'],
    },
    {
      id: 'gal-13',
      title: 'Humanoid Robot Mobile Base Configuration',
      caption: 'Student team testing differential drive wheels and obstacle sensing on their humanoid robot project.',
      school: 'Daffodils Public School',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'August 2026',
      category: 'robotics_ai',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-humanoid-robot-demo.jpg',
      tags: ['Humanoid', 'Differential Drive', 'Obstacle Sensing', 'Robotics'],
    },
    {
      id: 'gal-14',
      title: 'Precision Rover Wheel & Motor Assembly',
      caption: 'Students assembling high-torque DC geared motors and rubber tread wheels for line following competition.',
      school: 'Matrix High School',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'coding_stem',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-students-rover-hardware.jpg',
      tags: ['Assembly', 'DC Motors', 'Chassis', 'STEM'],
    },
    {
      id: 'gal-15',
      title: 'Multi-Sensor Chassis Debugging Session',
      caption: 'Students fine-tuning ultrasonic range finders and motor driver wiring on classroom workbenches.',
      school: 'Matrix High School',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'workshops_training',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-images/shorai-students-tuning-rover.jpg',
      tags: ['Debugging', 'Ultrasonic', 'Sensors', 'Workshop'],
    },
  ],
};
