import { GalleryData } from '@/types/gallery';

export const defaultGalleryData: GalleryData = {
  stats: {
    totalMilestones: '120+',
    activeCampusLabs: '50+',
    studentsReached: '10,000+',
    competitionsWon: '48+',
  },

  albums: [
    {
      id: 'album-dps-varanasi',
      slug: 'dps-varanasi-robotics-ai-ecosystem',
      schoolName: 'Delhi Public School, Varanasi',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      implementationDate: 'July 2026',
      headline: 'DPS Varanasi × Shorai: Flagship Robotics & AI Hub Launch',
      subtitle: 'Complete 30-day turnkey transformation of a 750 sq. ft. campus space into an advanced robotics, drone telemetry, and computer vision lab.',
      storyNarrative: 'In partnership with Shorai and SEG Academy (15+ years educational excellence), Delhi Public School Varanasi inaugurated its state-of-the-art STEM & AI Innovation Lab. Over 1,200 students from Grades 3 to 12 now engage in hands-on robotics engineering, micro-controller circuit building, and autonomous flight testing during weekly curriculum periods.',
      technologiesCovered: [
        'Robotics & Automation Bays',
        'Artificial Intelligence & Edge ML',
        'Autonomous Drone Aerodynamics',
        'IoT Microcontroller Stations',
        '3D Printing & Rapid Prototyping',
        'NEP 2020 Grade-Wise Progressive Pedagogy',
      ],
      heroImage: '/images/robotics_teacher_smart_class.jpg',
      galleryItemIds: ['gal-1', 'gal-2', 'gal-3', 'gal-4', 'gal-5'],
      outcomes: [
        '100% student enrollment across Middle and High School in weekly lab sessions',
        'Full-time on-campus certified Master Trainer deployed and managed by Shorai',
        'School team qualified for Regional World Robot Olympiad (WRO) 2026',
        'Aligned with Viksit Bharat @2047 national innovation roadmap',
      ],
      principalQuote: {
        quote: 'Shorai brought not just hardware kits, but a complete 360° turnkey transformation. The dedicated on-ground mentor, AI-powered LMS tracking, and structured NEP 2020 curriculum have created visible excitement among our students and parents.',
        author: 'Dr. S. K. Mukherjee',
        designation: 'Principal, DPS Varanasi',
      },
    },
    {
      id: 'album-kolkata-stem',
      slug: 'kolkata-stem-innovation-center',
      schoolName: 'Shorai STEM Innovation Campus (SEG Academy)',
      city: 'Kolkata',
      state: 'West Bengal',
      implementationDate: 'May 2026',
      headline: 'Kolkata Regional Research Hub: Autonomous Drone & AI Aviation',
      subtitle: 'Eastern India central hub for master faculty training, advanced robotics research, and inter-school hackathons.',
      storyNarrative: 'The Shorai Kolkata Research Campus (119/114 Ramkrishna Road, Khardaha) serves as the master pedagogical and testing center for school faculty across Eastern India. Here, teachers undergo 40 hours of rigorous hands-on enablement in AI tools, cyber security, and robotics before classroom deployment.',
      technologiesCovered: [
        'Drone Flight Simulators & ESC Tuning',
        '3D Additive Design & Slicing Workstations',
        'Python Embedded Logic Sandboxes',
        'Cyber Security & Safe Digital Citizenship',
      ],
      heroImage: '/images/shorai-quadrant-drone.jpg',
      galleryItemIds: ['gal-6', 'gal-7', 'gal-8', 'gal-9'],
      outcomes: [
        'Over 150 school educators certified in NEP 2020 STEM pedagogy',
        'Central flight testing cage for autonomous UAV obstacle navigation',
        'Incubated 12 student prototypes into regional science exhibitions',
      ],
    },
    {
      id: 'album-lucknow-public',
      slug: 'lucknow-public-school-ai-coding',
      schoolName: 'Lucknow Public Collegiate',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      implementationDate: 'August 2026',
      headline: 'Empowering 800+ Young Coders in Lucknow',
      subtitle: 'Transitioning from screen-only coding to tactile robotics, sensor integration, and real-world problem solving.',
      storyNarrative: 'Lucknow Public Collegiate partnered with Shorai to implement the 5-Stage Progressive Learning Journey. Students start with visual block logic in Primary and advance to Python, IoT sensors, and machine learning models in Senior Secondary.',
      technologiesCovered: [
        'Visual Block Programming (Scratch & Blockly)',
        'Arduino Embedded C++ Systems',
        'Line Following & Obstacle Avoidance Rovers',
        'IoT Weather Stations & Sensor Logging',
      ],
      heroImage: '/images/shorai-quadrant-coding.jpg',
      galleryItemIds: ['gal-10', 'gal-11', 'gal-12'],
      outcomes: [
        '24 student-built smart automation projects showcased at the Annual Science Fair',
        '100% curriculum compliance with CBSE Coding Skill Subject guidelines',
        '92% parent satisfaction reported during Termly Innovation Open Days',
      ],
    },
  ],

  transformations: [
    {
      id: 'trans-1',
      school: 'DPS Varanasi Campus',
      city: 'Varanasi, Uttar Pradesh',
      beforeDescription: 'Standard computer room with theoretical textbook lectures and zero hands-on electronics hardware.',
      beforeImage: '/images/shorai-quadrant-coding.jpg',
      transformationDetails: 'Installed 8 modular hexagonal workbenches, dedicated flight testing cage, complete sensor inventory, safety gear, and deployed a full-time Master Trainer in 21 days.',
      afterDescription: 'Fully active Innovation Lab where students build autonomous rovers, test drone ESC circuits, and write machine learning classifiers weekly.',
      afterImage: '/images/robotics_teacher_smart_class.jpg',
      impactMetrics: {
        studentsTrained: '1,200+',
        projectsBuilt: '45+',
        competitionsWon: '4 Regional Medals',
      },
    },
    {
      id: 'trans-2',
      school: 'Heritage Global School',
      city: 'Kolkata, West Bengal',
      beforeDescription: 'Disused science storage room with outdated display equipment.',
      beforeImage: '/images/shorai-quadrant-ai.jpg',
      transformationDetails: 'Renovated into an advanced AI & IoT Tinkering Bay with 3D printers, laser calibration, and smart micro-controllers under the Shorai 360° model.',
      afterDescription: 'Inter-school competition incubation zone with active student robotics teams winning Atal Tinkering Marathon awards.',
      afterImage: '/images/shorai-booming-robotics.jpg',
      impactMetrics: {
        studentsTrained: '650+',
        projectsBuilt: '32+',
        competitionsWon: '1st Prize State Innovation',
      },
    },
  ],

  items: [
    {
      id: 'gal-1',
      title: 'Autonomous Obstacle Rover Calibration',
      caption: 'Grade 8 students at DPS Varanasi configuring ultrasonic sensors and motor drivers on their autonomous obstacle rover.',
      school: 'Delhi Public School',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'August 2026',
      category: 'robotics_ai',
      aspectRatio: 'landscape',
      imageUrl: '/images/robotics_teacher_smart_class.jpg',
      tags: ['Robotics', 'Ultrasonic Sensors', 'Arduino', 'Middle School'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-2',
      title: 'Educational Quadcopter Aerodynamics Test',
      caption: 'Middle school students testing drone thrust, gyro stabilization, and telemetry flight control at the campus testing zone.',
      school: 'Delhi Public School',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'drone_aviation',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-quadrant-drone.jpg',
      tags: ['Drones', 'Aerodynamics', 'Flight Controller', 'Telemetry'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-3',
      title: 'Tactile Breadboard Circuit Experimentation',
      caption: 'Students assembling LED matrix arrays and infrared proximity detectors using modular micro-controller boards.',
      school: 'Delhi Public School',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'coding_stem',
      aspectRatio: 'square',
      imageUrl: '/images/shorai-quadrant-coding.jpg',
      tags: ['Circuits', 'Breadboard', 'STEM', 'Electronics'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-4',
      title: 'Inauguration of Turnkey Innovation Lab',
      caption: 'School Trustees and Academic Directors cutting the ribbon for the new Shorai 360° AI & Robotics Lab on campus.',
      school: 'Delhi Public School',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'inaugurations_atl',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-quadrant-ai.jpg',
      tags: ['Inauguration', 'Leadership', 'Turnkey Setup', 'Lab Launch'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-5',
      title: 'Regional WRO Championship Gold Medalists',
      caption: 'DPS Varanasi student robotics squad celebrating 1st place in the Regional World Robot Olympiad qualifier.',
      school: 'Delhi Public School',
      schoolSlug: 'dps-varanasi-robotics-ai-ecosystem',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      date: 'August 2026',
      category: 'competitions_wro',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-booming-robotics.jpg',
      tags: ['WRO', 'Gold Medal', 'Championship', 'Competition'],
      albumId: 'album-dps-varanasi',
    },
    {
      id: 'gal-6',
      title: 'Faculty AI Enablement & Lesson Planning',
      caption: 'Teachers undergoing rigorous 40-hour hands-on training at the Shorai Kolkata Innovation Center in responsible AI tools.',
      school: 'Shorai STEM Center (SEG Academy)',
      schoolSlug: 'kolkata-stem-innovation-center',
      city: 'Kolkata',
      state: 'West Bengal',
      date: 'June 2026',
      category: 'workshops_training',
      aspectRatio: 'landscape',
      imageUrl: '/images/robotics_teacher_smart_class.jpg',
      tags: ['Faculty Training', 'NEP 2020', 'Teacher Enablement', 'AI Tools'],
      albumId: 'album-kolkata-stem',
    },
    {
      id: 'gal-7',
      title: 'Drone Aerodynamics & ESC Tuning Workshop',
      caption: 'Master faculty session on electronic speed controllers (ESC), brushless DC motors, and flight software tuning.',
      school: 'Shorai STEM Center (SEG Academy)',
      schoolSlug: 'kolkata-stem-innovation-center',
      city: 'Kolkata',
      state: 'West Bengal',
      date: 'May 2026',
      category: 'drone_aviation',
      aspectRatio: 'square',
      imageUrl: '/images/shorai-quadrant-drone.jpg',
      tags: ['Drones', 'Teacher Training', 'Aviation', 'Hardware'],
      albumId: 'album-kolkata-stem',
    },
    {
      id: 'gal-8',
      title: 'Computer Vision Sorter Model Deployment',
      caption: 'High school students demonstrating real-time object classification and smart conveyor sorting trained on edge AI hardware.',
      school: 'Heritage Global School',
      city: 'Kolkata',
      state: 'West Bengal',
      date: 'May 2026',
      category: 'robotics_ai',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-quadrant-ai.jpg',
      tags: ['Computer Vision', 'Edge AI', 'Object Detection', 'High School'],
    },
    {
      id: 'gal-9',
      title: 'Visual Block to Python Progression Bootcamp',
      caption: 'Grade 6 students transitioning from visual drag-and-drop block coding into structured Python algorithm scripting.',
      school: 'Lucknow Public Collegiate',
      schoolSlug: 'lucknow-public-school-ai-coding',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      date: 'August 2026',
      category: 'coding_stem',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-quadrant-coding.jpg',
      tags: ['Python', 'Block Coding', 'CBSE Coding', 'Grade 6'],
      albumId: 'album-lucknow-public',
    },
    {
      id: 'gal-10',
      title: 'IoT Environmental Sensor Array Build',
      caption: 'Students assembling real-time DHT22 temperature, humidity, and air quality telemetry nodes sending data to the Shorai LMS.',
      school: 'Lucknow Public Collegiate',
      schoolSlug: 'lucknow-public-school-ai-coding',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      date: 'August 2026',
      category: 'coding_stem',
      aspectRatio: 'portrait',
      imageUrl: '/images/shorai-booming-robotics.jpg',
      tags: ['IoT', 'Sensors', 'Telemetry', 'STEM'],
      albumId: 'album-lucknow-public',
    },
    {
      id: 'gal-11',
      title: 'Line Following Rover Speed Challenge',
      caption: 'Middle school students tuning PID loop constants on dual-photodiode sensor rovers during the campus innovation sprint.',
      school: 'Lucknow Public Collegiate',
      schoolSlug: 'lucknow-public-school-ai-coding',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      date: 'July 2026',
      category: 'robotics_ai',
      aspectRatio: 'square',
      imageUrl: '/images/robotics_teacher_smart_class.jpg',
      tags: ['PID Controller', 'Rovers', 'Robotics', 'Middle School'],
      albumId: 'album-lucknow-public',
    },
    {
      id: 'gal-12',
      title: 'State Science Fair 1st Prize Presentation',
      caption: 'Student robotics innovators receiving first prize trophy at the State Technology Innovation Expo for automated campus solar tracker.',
      school: 'Heritage Global School',
      city: 'Kolkata',
      state: 'West Bengal',
      date: 'June 2026',
      category: 'competitions_wro',
      aspectRatio: 'landscape',
      imageUrl: '/images/shorai-quadrant-drone.jpg',
      tags: ['Science Fair', '1st Prize', 'Solar Tracker', 'State Award'],
    },
  ],
};
